services:
  web:
    build: .
    ports:
      - 5000:5000    
    depends_on:
      es: 
        condition: service_healthy
          
          
  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.3.2"    
    ports: 
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
    healthcheck:
      test: ["CMD-SHELL", "curl host.docker.internal:9200"]
      interval: 30s
      timeout: 30s
      retries: 5
    #restart: unless-stopped